#!/bin/bash -l
#SBATCH -A g92-1496
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --job-name=ffhq_pretrain
#SBATCH --time=12:00:00
#SBATCH --gres=gpu:volta:4
#SBATCH --constraint=volta32G

# Load modules
module purge 2>&1 >/dev/null
module load \
  gpu/cuda/11.7 \
  common/git/2.27.0 \
  common/anaconda/3.8 \
  common/compilers/nvidia/21.2 \
  common/compilers/gcc/9.3.1

# Load Python env
. activate ./env

# Run training
CC=gcc CXX=g++ \
WANDB_ENTITY=video_uw2022 \
WANDB_PROJECT=ffhq-pretrain \
python3 src/infra/launch.py \
  hydra.run.dir=. \
  exp_suffix=ffhq_pretrain \
  env=local \
  dataset=ffhq \
  dataset.name=ffhq_vids \
  dataset.resolution=256 \
  +overwrite=true \
  +training.resume=latest \
  training.kimg=5000 \
  training.snap=100 \
  num_gpus=4
