#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --job-name=ffs_256_concat_w
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:volta:4
#SBATCH --constraint=volta32G

# Load modules
module purge 2>&1 >/dev/null
module load \
  gpu/cuda/11.7 \
  common/git/2.27.0 \
  common/anaconda/3.8 \
  common/compilers/nvidia/21.2 \
  common/compilers/gcc/9.3.1

# Load Python env
. activate ./env

# Run training
CC=gcc CXX=g++ \
python3 src/infra/launch.py \
  hydra.run.dir=. \
  exp_suffix=ffs_256_concat_w \
  env=local \
  dataset=ffs \
  dataset.name=ffs_processed \
  dataset.resolution=256 \
  +ignore_uncommited_changes=true \
  +overwrite=true \
  +generator.time_enc.cond_type=concat_w \
  num_gpus=4
