#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --job-name=ffs_256+max_dist8
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:volta:4
#SBATCH --constraint=volta32G

# Load modules
module purge 2>&1 >/dev/null
module load \
  gpu/cuda/11.7 \
  common/git/2.27.0 \
  common/anaconda/3.8 \
  common/compilers/nvidia/21.2 \
  common/compilers/gcc/9.3.1

# Load Python env
. activate ./env

# Run training
CC=gcc CXX=g++ \
WANDB_ENTITY=video_uw2022 \
WANDB_PROJECT=max_dist \
WANDB_NAME="num_frames_per_video=8" \
python3 src/infra/launch.py \
  hydra.run.dir=. \
  exp_suffix=ffs_256_max_dist8_v2 \
  env=local \
  dataset=ffs \
  dataset.name=ffs_processed \
  dataset.resolution=256 \
  +overwrite=true \
  +training.resume=latest \
  sampling.num_frames_per_video=8 \
  sampling.total_dists="" \
  sampling.max_dist=86 \
  training.batch_size=16 \
  num_gpus=4
