#!/bin/bash -l
#SBATCH -A g92-1496
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --job-name=ffs_finetune
#SBATCH --time=12:00:00
#SBATCH --gres=gpu:volta:4
#SBATCH --constraint=volta32G

# Load modules
module purge 2>&1 >/dev/null
module load \
  gpu/cuda/11.7 \
  common/git/2.27.0 \
  common/anaconda/3.8 \
  common/compilers/nvidia/21.2 \
  common/compilers/gcc/9.3.1

# Load Python env
. activate ./env

# Run training
CC=gcc CXX=g++ \
WANDB_ENTITY=video_uw2022 \
WANDB_PROJECT=ffs-finetune \
python3 src/infra/launch.py \
  hydra.run.dir=. \
  exp_suffix=ffs_finetune \
  env=local \
  dataset=ffs \
  dataset.name=ffs_processed \
  dataset.resolution=256 \
  +overwrite=true \
  +training.resume="$(pwd)/ckpts/ffhq_pretrain.pkl" \
  training.kimg=20000 \
  training.snap=100 \
  training.freezed=8 \
  training.freezeg=4 \
  num_gpus=4
