#!/usr/bin/bash -l
#SBATCH --job-name=tar-ffs
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=24:00:00
#SBATCH --gres=cpuonly

cd $HOME/vg/stylegan-v/data
tar -cf ffs_processed.tar ffs_processed/
