#!/usr/bin/bash -l
#SBATCH -p plgrid-gpu-a100 
#SBATCH -A plgso2023-gpu-a100 
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH --gres=gpu:1
#SBATCH --job-name=test

conda activate ./env

EXP_NAME="test"

# Run training
CC=gcc CXX=g++ \
WANDB_ENTITY=video_uw2022 \
WANDB_PROJECT=${EXP_NAME} \
python3 src/infra/launch.py \
  hydra.run.dir=. \
  exp_suffix=${EXP_NAME} \
  env=local \
  dataset=ffs \
  dataset.name=ffs_processed \
  dataset.resolution=256 \
  +ignore_uncommited_changes=true \
  +overwrite=true \
  training.kimg=2500 \
  training.batch_size=32 \
  num_gpus=1