#!/usr/bin/bash -l
#SBATCH -p plgrid-gpu-a100 
#SBATCH -A plgso2023-gpu-a100 
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=4:00:00
#SBATCH --gres=gpu:2
#SBATCH --job-name=athena-test

# Reload modules
module purge
module load \
  CUDA/11.3.1 \
  OpenMPI/4.1.1 \
  GCC/10.3.0 \
  GCCcore/10.3.0 \
  Python/3.9.5 \
  SciPy-bundle/2021.05 \
  Pillow/8.2.0 \
  OpenCV/4.5.3-CUDA-11.3.1-contrib \
  Ninja/1.10.2 \
  tensorboard/2.8.0 \
  tqdm/4.61.2 \
  matplotlib/3.4.2

# Load Python venv
. ./env/bin/activate